spring:
datasource:
  username: root
  password: a62134787
  url: jdbc:mysql://localhost:3306/msr_pm
  driver-class-name: com.mysql.cj.jdbc.Driver
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
application:
  name: msrpm-es

mybatis-plus:
  mapper-locations: classpath:com/msr/msrpm/es/mapper/xml/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 5101
