#spring:
#datasource:
#  username: root
#  password: 123456
#  url: jdbc:mysql://localhost:3306/msr_pm
##  url: jdbc:mysql://localhost:3306/msr_pm?characterEncoding=utf-8&serverTimezone=GMT%2B9
#  driver-class-name: com.mysql.cj.jdbc.Driver
#jackson:
#  date-format: yyyy-MM-dd HH:mm:ss
##  timezone: GMT+9
#application:
#  name: msrpm-rm
#
#mybatis-plus:
#  mapper-locations: classpath:com/msr/msrpm/rm/mapper/xml/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: 1
#      logic-not-delete-value: 0
##      db-type: mysql
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#server:
#  port: 5301
